SET IDENTITY_INSERT [dbo].[REQUEST_LIST_TABLE] ON
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (1, 1)
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (2, 1)
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (3, 1)
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (4, 1)
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (5, 1)
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (6, 1)
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (7, 1)
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (8, 1)
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (9, 1)
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (10, 1)
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (11, 2)
INSERT INTO [dbo].[REQUEST_LIST_TABLE] ([SOFTWARE_REQUEST_ID], [SOFTWARE_ID]) VALUES (12, 2)
SET IDENTITY_INSERT [dbo].[REQUEST_LIST_TABLE] OFF
